# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('customer_id', models.IntegerField(default=0)),
                ('amt_deposited', models.DecimalField(decimal_places=2, max_digits=6)),
                ('balance_amt', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='daily_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('number_plate', models.CharField(max_length=100)),
                ('load_type', models.CharField(max_length=100)),
                ('tonnes', models.IntegerField(default=0)),
                ('trips', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('employee_name', models.CharField(max_length=100)),
                ('amt_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('balance_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('employee_id', models.IntegerField(default=0)),
                ('phone_contact', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='repairs_maintanace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('mechanic_name', models.CharField(max_length=100)),
                ('amt_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('balance_amt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('part_name', models.CharField(max_length=100)),
                ('part_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iveco.daily_work'),
        ),
    ]
